apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  annotations:
    strategy.spinnaker.io/max-version-history: '2'
  labels:
    applicationName: maggie-k8s-demo
  name: maggie-k8s-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      applicationName: maggie-k8s-demo
  template:
    metadata:
      labels:
        applicationName: maggie-k8s-demo
    spec:
      containers:
        - image: gcr.io/spinnaker-maggie/spinnaker-kubernetes-demo
          name: primary
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000