apiVersion: v1
data:
  entrypoint.sh: |-
    #!/bin/bash
    GREETING=hello
    while true; do echo ${GREETING}; sleep 5; done
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: default
---
apiVersion: v1
data:
  alive.sh: |-
    #!/bin/bash
    IM_ALIVE=alive
    echo ${IM_ALIVE}
kind: ConfigMap
metadata:
  name: my-configmap-2
  namespace: default
---