kind: Service
apiVersion: v1
metadata:
  name: maggie-k8s-demo
  namespace: default
spec:
  selector:
    app: maggie-k8s-demo
    version: v0
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000